DATALOADER:
  SIZE_DIVISIBILITY: 32
DATASETS:
  TEST:
  - VID_val_videos
  TRAIN:
  - DET_train_30classes
  - VID_train_15frames
INPUT:
  MIN_SIZE_TRAIN:
  - 600
MODEL:
  BACKBONE:
    CONV_BODY: R-101-FPN
  META_ARCHITECTURE: GeneralizedRCNNMEGA
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    RES5_DILATION: 2
  ROI_BOX_HEAD:
    CONV_HEAD_DIM: 256
    FEATURE_EXTRACTOR: MEGAFPNFeatureExtractor
    MLP_HEAD_DIM: 1024
    NUM_CLASSES: 31
    NUM_STACKED_CONVS: 4
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
    POOLER_SCALES:
    - 0.25
    - 0.125
    - 0.0625
    - 0.03125
    PREDICTOR: FPNPredictor
    USE_GN: false
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    BBOX_REG_WEIGHTS:
    - 10.0
    - 10.0
    - 5.0
    - 5.0
    DETECTIONS_PER_IMG: 300
    USE_FPN: true
  RPN:
    ANCHOR_SIZES:
    - 32
    - 64
    - 128
    - 256
    - 512
    ANCHOR_STRIDE:
    - 4
    - 8
    - 16
    - 32
    - 64
    FPN_POST_NMS_PER_BATCH: true
    FPN_POST_NMS_TOP_N_TEST: 300
    FPN_POST_NMS_TOP_N_TRAIN: 300
    POST_NMS_TOP_N_TEST: 300
    POST_NMS_TOP_N_TRAIN: 300
    PRE_NMS_TOP_N_TEST: 1000
    PRE_NMS_TOP_N_TRAIN: 1000
    USE_FPN: true
  VID:
    METHOD: mega
    ROI_BOX_HEAD:
      ATTENTION:
        ENABLE: true
        STAGE: 3
      REDUCE_CHANNEL: false
    RPN:
      REF_POST_NMS_TOP_N: 75
      REF_PRE_NMS_TOP_N: 1000
SOLVER:
  TEST_PERIOD: 2500
